"""empty message

Revision ID: 07b296d78248
Revises: 4ef8fac133d2
Create Date: 2022-06-21 13:49:46.454072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b296d78248'
down_revision = '4ef8fac133d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('date_posted', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'date_posted')
    # ### end Alembic commands ###
