"""empty message

Revision ID: 1c12706f65e9
Revises: e3eec5943537
Create Date: 2022-07-22 20:24:20.231945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c12706f65e9'
down_revision = 'e3eec5943537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('date_posted', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'date_posted')
    # ### end Alembic commands ###
