"""empty message

Revision ID: 39f77075ff6f
Revises: f5aa1b79092a
Create Date: 2022-06-20 07:28:07.649463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f77075ff6f'
down_revision = 'f5aa1b79092a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'products', 'user', ['user_id'], ['id'])
    op.drop_column('products', 'product_image')
    op.drop_column('products', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('likes', sa.INTEGER(), nullable=False))
    op.add_column('products', sa.Column('product_image', sa.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    # ### end Alembic commands ###
