"""empty message

Revision ID: 8040818b45da
Revises: f5a1233776b8
Create Date: 2022-06-20 00:03:14.859596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8040818b45da'
down_revision = 'f5a1233776b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_foreign_key(None, 'products', 'user', ['user_id'], ['id'])
    op.drop_column('products', 'likes')
    op.drop_column('products', 'product_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_image', sa.VARCHAR(length=20), nullable=False))
    op.add_column('products', sa.Column('likes', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'product_price')
    # ### end Alembic commands ###
