"""empty message

Revision ID: e3eec5943537
Revises: 7a8eccc55391
Create Date: 2022-07-18 23:03:00.685764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3eec5943537'
down_revision = '7a8eccc55391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'date_posted',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'date_posted',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
