"""empty message

Revision ID: f5aa1b79092a
Revises: 5cb398ce3bd0
Create Date: 2022-06-20 07:19:49.104192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5aa1b79092a'
down_revision = '5cb398ce3bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'products', 'user', ['user_id'], ['id'])
    op.drop_column('products', 'likes')
    op.drop_column('products', 'product_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_image', sa.VARCHAR(length=20), nullable=False))
    op.add_column('products', sa.Column('likes', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    # ### end Alembic commands ###
